version: '3'

services:
    laravel-11-docker:
       build:
           args:
             user:laravel-11-docker
             uid:1000
           context: ./
           dockerfile: DockerFile
       image: laravel-11-docker-image
       container_name : laravel-11-app
       restart: unless-stopped
       working_dir: /var/www
       volumes:
            -   ./:/var/www
       networks:
            - laravel-11-app-network



